#!/usr/bin/env bash
set -eo pipefail

for (( i=0; i <= $#; i++ )); do
  declare -x "ARG$i"="${!i}"
done

# Automatically generated by moon. DO NOT MODIFY!
# https://moonrepo.dev/docs/guides/vcs-hooks

unset GIT_INDEX_FILE; moon run :format-check
unset GIT_INDEX_FILE; moon run :typecheck

