name: Deploy App

on:
    pull_request:
        branches:
            - main
    push:
        branches:
            - main

permissions:
    checks: write
    contents: read
    pull-requests: write

jobs:
    build:
        name: Audit and build
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Install pnpm
              uses: pnpm/action-setup@v4
              with:
                  run_install: false

            - name: Use Node 22
              uses: actions/setup-node@v4
              with:
                  node-version: '22'
                  cache: 'pnpm'

            - name: Install dependencies
              run: pnpm install

            - name: Check format
              run: pnpm run format:check

            - name: Check Lint
              run: pnpm run lint

            - name: Build project
              run: pnpm run build

            - name: Upload artifact
              uses: actions/upload-artifact@v4
              with:
                  name: build
                  path: dist/

    deploy-preview:
        name: Deploy Preview
        if: ${{ github.event_name == 'pull_request' }}
        needs: build
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Download artifact
              uses: actions/download-artifact@v4
              with:
                  name: build
                  if-no-files-found:: error

            - name: Deploy app
              uses: FirebaseExtended/action-hosting-deploy@v0
              with:
                  repoToken: ${{ secrets.GITHUB_TOKEN }}
                  firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_TRACKSY_APP }}
                  projectId: tracksy-app
              env:
                  FIREBASE_CLI_EXPERIMENTS: webframeworks

    deploy-live:
        name: Deploy Live
        if: ${{ github.event_name == 'push' }}
        needs: build
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Download artifact
              uses: actions/download-artifact@v4
              with:
                  name: build
                  if-no-files-found:: error

            - name: Deploy app
              uses: FirebaseExtended/action-hosting-deploy@v0
              with:
                  repoToken: ${{ secrets.GITHUB_TOKEN }}
                  firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_TRACKSY_APP }}
                  channelId: live
                  projectId: tracksy-app
              env:
                  FIREBASE_CLI_EXPERIMENTS: webframeworks
