name: Deploy functions

on:
    push:
        branches:
            - main

jobs:
    app:
        name: Audit, build, test and deploy
        runs-on: ubuntu-latest
        defaults:
          run:
            working-directory: ./functions
        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Use Node 22
              uses: actions/setup-node@v4
              with:
                  node-version: '22'

            - name: Install dependencies
              working-directory: ./functions/functions
              run: npm install

            - name: Check format
              working-directory: ./functions/functions
              run: npm run format

            - name: Check Lint
              working-directory: ./functions/functions
              run: npm run lint

            - name: Build project
              working-directory: ./functions/functions
              run: npm run build

            - name: Deploy functions
              env:
                  FIREBASE_SERVICE_ACCOUNT_TRACKSY_APP: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_TRACKSY_FUNCTIONS }}
                  SPOTIFY_CLIENT_ID: ${{ secrets.SPOTIFY_CLIENT_ID }}
                  SPOTIFY_CLIENT_SECRET: ${{ secrets.SPOTIFY_CLIENT_SECRET }}
              run: |
                npm install -g firebase-tools
                echo "$FIREBASE_SERVICE_ACCOUNT_TRACKSY_APP" | base64 --decode > $HOME/firebase-key.json
                echo "SPOTIFY_CLIENT_ID=$SPOTIFY_CLIENT_ID" >> ./functions/.env
                echo "SPOTIFY_CLIENT_SECRET=$SPOTIFY_CLIENT_SECRET" >> ./functions/.env
                export GOOGLE_APPLICATION_CREDENTIALS=$HOME/firebase-key.json
                firebase deploy
