name: Sync Github labels

on:
  push:
    branches:
      - main
    paths:
      - .github/labels.yml
      - .github/workflows/deploy-labels.yml
  workflow_dispatch:

permissions:
  issues: write

jobs:
  sync-labels:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: EndBug/label-sync@v2
        with:
          config-file: .github/labels.yml
          delete-other-labels: false
