name: App preview

on:
    pull_request:
        types: [labeled]
        paths:
          - "app/**"
          - ".github/workflows/deploy-app-preview.yml"
    workflow_dispatch:

permissions:
    checks: write
    contents: read
    pull-requests: write

jobs:
    app:
        name: Audit, build and deploy
        runs-on: ubuntu-latest
        if: contains(github.event.label.name, 'deploy-preview')
        defaults:
          run:
            working-directory: ./app
        env:
          PUBLIC_SPOTIFY_CLIENT_ID: ${{ secrets.SPOTIFY_CLIENT_ID }}
          PUBLIC_DEMO_JSON_URL: ${{ vars.PUBLIC_DEMO_JSON_URL }}

        steps:
            - name: Checkout code
              uses: actions/checkout@v5

            - name: Install pnpm
              uses: pnpm/action-setup@v4
              with:
                  run_install: false

            - name: Use Node 20
              uses: actions/setup-node@v5
              with:
                  node-version: '22'
                  cache: 'pnpm'

            - name: Install dependencies
              run: pnpm install

            - name: Audit dependencies
              continue-on-error: true
              run: pnpm audit --prod

            - name: Check format
              run: pnpm run format:check

            - name: Check Lint
              run: pnpm run lint

            - name: Check test
              run: pnpm run test:coverage

            - name: Build project
              run: pnpm run build

            - name: Deploy preview
              uses: FirebaseExtended/action-hosting-deploy@v0
              with:
                  repoToken: ${{ secrets.GITHUB_TOKEN }}
                  firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_TRACKSY_APP }}
                  projectId: tracksy-app
                  entryPoint: ./app
              env:
                  FIREBASE_CLI_EXPERIMENTS: webframeworks
