name: Deploy App

on:
    pull_request:
        branches:
            - main
    push:
        branches:
            - main

permissions:
    checks: write
    contents: read
    pull-requests: write

jobs:
    deploy-preview:
        name: Deploy Preview
        if: ${{ github.event_name == 'pull_request' }}
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - uses: ./.github/actions/build

            - name: Deploy app
              uses: FirebaseExtended/action-hosting-deploy@v0
              with:
                  repoToken: ${{ secrets.GITHUB_TOKEN }}
                  firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_TRACKSY_APP }}
                  projectId: tracksy-app
              env:
                  FIREBASE_CLI_EXPERIMENTS: webframeworks

    deploy-live:
        name: Deploy Live
        if: ${{ github.event_name == 'push' }}
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - uses: ./.github/actions/build

            - name: Deploy app
              uses: FirebaseExtended/action-hosting-deploy@v0
              with:
                  repoToken: ${{ secrets.GITHUB_TOKEN }}
                  firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_TRACKSY_APP }}
                  channelId: live
                  projectId: tracksy-app
              env:
                  FIREBASE_CLI_EXPERIMENTS: webframeworks
