name: App live

on:
    push:
        branches:
            - main
    workflow_dispatch:

permissions:
    contents: read

jobs:
    app:
        name: Audit, build and deploy
        runs-on: ubuntu-latest
        defaults:
          run:
            working-directory: ./app
        env:
          PUBLIC_SPOTIFY_CLIENT_ID: ${{ secrets.SPOTIFY_CLIENT_ID }}
          PUBLIC_DEMO_JSON_URL: ${{ variables.PUBLIC_DEMO_JSON_URL }}

        steps:
            - name: Checkout code
              uses: actions/checkout@v5

            - name: Install pnpm
              uses: pnpm/action-setup@v4
              with:
                  run_install: false

            - name: Use Node 20
              uses: actions/setup-node@v4
              with:
                  node-version: '22'
                  cache: 'pnpm'

            - name: Install dependencies
              run: pnpm install

            - name: Check format
              run: pnpm run format:check

            - name: Check Lint
              run: pnpm run lint

            - name: Build project
              run: pnpm run build


            - name: Deploy app
              uses: FirebaseExtended/action-hosting-deploy@v0
              with:
                  repoToken: ${{ secrets.GITHUB_TOKEN }}
                  firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_TRACKSY_APP }}
                  channelId: live
                  projectId: tracksy-app
                  entryPoint: ./app
              env:
                  FIREBASE_CLI_EXPERIMENTS: webframeworks
