name: Test functions

on:
    pull_request:
        branches:
            - main

jobs:
    app:
        name: Audit, build and test
        runs-on: ubuntu-latest
        defaults:
          run:
            working-directory: ./functions
        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Use Node 22
              uses: actions/setup-node@v4
              with:
                  node-version: '22'

            - name: Install dependencies
              working-directory: ./functions/functions
              run: npm install

            - name: Check format
              working-directory: ./functions/functions
              run: npm run format

            - name: Check Lint
              working-directory: ./functions/functions
              run: npm run lint

            - name: Build project
              working-directory: ./functions/functions
              run: npm run build
