name: Build

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
    paths:
      - "synthetic-datasets/synthetic_datasets/**/*.py"
      - "synthetic-datasets/pyproject.toml"
      - "synthetic-datasets/uv.lock"
      - ".github/workflows/test-synthetic-datasets.yml"

permissions:
  contents: read

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./synthetic-datasets

    strategy:
      matrix:
        python-version:
          - "3.12"
          - "3.13"

    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          version: "0.5.11"

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install the project
        run: uv sync --all-extras --dev

      - name: Run lint
        run: uv run ruff check
